### ISSUE TITLE
Location of workouts showing as unknown

### ISSUE THREAD

**Issue by nrevolt** [jovandeginste/workout-tracker#160]
After importing workout from 05/27/2024, I noticed that it's Location was unknown, all previous workouts showed correct City, Province.

I refreshed all workouts, and the location to all previously imported workouts, also changed to unknown location. Deleted a workout and re-imported, same problem.  I had recently switched from Chrome to Firefox, and thought that may have been the issue, so I launched Chrome and logged into Workout-Tracker in Chrome, refresh all workouts, and tried re-importing a workout same problem.

Using most current version:  branch master (0fe05a80)
Also tried downgrading to:   v0.14.1 (0e6f0c5b) issue persists

**Comment by jovandeginste** [comment]
Could you provide me with a sample gpx?

**Comment by nrevolt** [comment]
[20240529_140526.zip](https://github.com/jovandeginste/workout-tracker/files/15504127/20240529_140526.zip)

**Comment by nrevolt** [comment]
On the off chance that Samsung made some changes, here is a gpx file from last month, that showed the correct location, (Toronto, Ontario) prior to this week when I did a refresh.

[20220407_180347.zip](https://github.com/jovandeginste/workout-tracker/files/15504143/20220407_180347.zip)

**Comment by jovandeginste** [comment]
Which version are you using?

**Comment by jovandeginste** [comment]
If you are running a release version (and not master), this could be the same issue as #146 

This is fixed, but not yet released.

**Comment by nrevolt** [comment]
> Which version are you using?

Was running branch master (0fe05a80) when I first noticed the problem.
Just updated to branch master (0d0101d1) and refreshed workouts, problem persists.

In case it matters, running in Docker under Unraid and repository is: ghcr.io/jovandeginste/workout-tracker:master

**Comment by jovandeginste** [comment]
Does the container have access to the internet? It uses openstreetmap to convert lat/lon to an address.
When I update the workout, it says "Toronto" ...

**Comment by nrevolt** [comment]
The container does have access to the internet, and I am able to ping openstreetmaps.org from a console opened from the container as per the attached screencap. I did a fresh install and problem persists. 
![chrome_mL1HYJhm2A](https://github.com/jovandeginste/workout-tracker/assets/140467280/becfd659-3c22-4a96-82c2-63c4a7c40b95)

**Comment by betov69** [comment]
Hello all, I present the same error, I share the information so that we can solve this problem, excuse my English, greetings

Version Workout: [branch docker-arm (c88c551d)]
Version RunnerUp: v2.6.0.2

[RunnerUp_SM-A525M_2024-06-01-07-57-31_Running.zip](https://github.com/user-attachments/files/15522542/RunnerUp_SM-A525M_2024-06-01-07-57-31_Running.zip)

![firefox_ayH2zP8d7A](https://github.com/jovandeginste/workout-tracker/assets/90874504/a297bbcf-7f06-4889-b943-e62395ea7fff)

**Comment by jovandeginste** [comment]
@betov69 could you make sure you use the latest release? When I import your gpx, I get the correct location:

![image](https://github.com/jovandeginste/workout-tracker/assets/3170771/f5e728ff-9188-48b4-b6a9-bd853bf884c7)

**Comment by betov69** [comment]
Hello, thank you very much for responding, I just updated the version of the docker container to the:  Workout Tracker, v0.15.0 (0fe05a80)

![imagen](https://github.com/jovandeginste/workout-tracker/assets/90874504/c939786d-27bb-4267-b309-aa4ba6aad76c)


```
workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:latest
    restart: unless-stopped
```

 Unfortunately I still have the same problem. As additional information, I remember that I recently added two additional options:

```
- WT_REGISTRATION_DISABLED=1
- WT_SOCIALS_DISABLED=1
```

but I highly doubt that they are related to the problem, I even added the training of the colleague from Toronto and it also appeared to me as unknown, I don't know what is happening

**Comment by nrevolt** [comment]
Upgraded to ghcr.io/jovandeginste/workout-tracker:latest, and problem persists.

You mentioned the two additional options you recently added, and like  you doubted they related to the problem, however it was around the same time I implemented the two options as variables, that the unknown location problem started. Never brought it up previously since a fresh install into a new docker image, and a different data folder continued to show the problem.

**Comment by jovandeginste** [comment]
I'll add debug information in a next release

**Comment by betov69** [comment]
Thank you very much

**Comment by jovandeginste** [comment]
The current version already has DEBUG logging. If you run with `WT_DEBUG=true`, and add the GPX (or refresh the workout), you should get a line like this:

```
9:56AM INF SQL query executed [22.404436ms] app=workout-tracker version=master sha=44bb39cd4d0d78e7d412d00b9b01745dbe2cfdc2 module=database query="INSERT INTO `map_data` (`created_at`,`updated_at`,`deleted_at`,`workout_id`,`creator`,`name`,`center`,`address`,`total_distance`,`total_duration`,`max_speed`,`pause_duration`,`min_elevation`,`max_elevation`,`total_up`,`total_down`,`points`,`id`) VALUES (\"2024-05-31 18:25:23.606\",\"2024-06-03 09:56:35.386\",NULL,219,\"Samsung Health_0.2\",\"20240529_140526.gpx\",\"{\"\"Lat\"\":43.69838552092704,\"\"Lng\"\":-79.30457942134832}\",\"{\"\"FormattedAddress\"\":\"\"Taylor Creek Trail, Woodbine Heights, Beaches—East York, East York, Toronto, Golden Horseshoe, Ontario, M4C 4T4, Canada\"\",\"\"Street\"\":\"\"Taylor Creek Trail\"\",\"\"HouseNumber\"\":\"\"\"\",\"\"Suburb\"\":\"\"East York\"\",\"\"Postcode\"\":\"\"M4C 4T4\"\",\"\"State\"\":\"\"Ontario\"\",\"\"StateCode\"\":\"\"\"\",\"\"StateDistrict\"\":\"\"\"\",\"\"County\"\":\"\"\"\",\"\"Country\"\":\"\"Canada\"\",\"\"CountryCode\"\":\"\"CA\"\",\"\"City\"\":\"\"Toronto\"\"}\",3024.907481902884,2154000000000,1.6835604768216892,5000000005,135.05223233170423,141.29623233170423,29.978099999999912,28.988099999999918,NULL,231) ON CONFLICT (`id`) DO UPDATE SET `workout_id`=`excluded`.`workout_id` RETURNING `id`" duration=22.404436ms rows=1 file=/workout-tracker/pkg/database/workouts.go:220
```

Could you verify the `Lat`, `Lng` and `FormattedAddress` in the output? As you can see, the address contains the full address of the center of the workout.

**Comment by betov69** [comment]
Hello, thank you very much for following up on my problem, I really appreciate it, I enabled the Debug option to true and updated the training as you mentioned, it took me a lot of work to check the log but I didn't find the information you asked for:

>
2024-06-03T15:30:53.548375389Z INFO msg=SQL query executed [2.9261ms] app=workout-tracker version=v0.15.0 sha=0fe05a807206885e10716cad2f1978d995331c5c module=database query=INSERT INTO `gpx_data` (`created_at`,`updated_at`,`deleted_at`,`workout_id`,`content`,`checksum`,`filename`,`id`) VALUES ("2024-06-03 15:28:00.646","2024-06-03 15:28:00.646",NULL,124,"<binary>","<binary>","RunnerUp_SM-A525M_2024-06-01-07-57-31_Running.gpx",124) ON CONFLICT (`id`) DO UPDATE SET `workout_id`=`excluded`.`workout_id` RETURNING `id` duration=2926100 rows=1 file=/app/pkg/database/workouts.go:210

I hope it is useful, I am waiting, thank you and greetings

**Comment by jovandeginste** [comment]
No, I need the line matching `INSERT INTO map_data`... Maybe remove the workout and add it back?

**Comment by betov69** [comment]
The line you mention does not appear, let me tell you what I do to know if it is correct:

- Add the option -WT_DEBUG=true in my docker configuration and repull image

- I deleted the training and uploading it, 

- Review the application logs

Is it the correct way or did I forget to omit something, I appreciate the feedback

**Comment by betov69** [comment]
Hello, thank you very much for the feedback, of course it is but I will have to do it at night, as soon as I do the clean installation I will comment on the results, again thank you very much

**Comment by betov69** [comment]
Good evening, I just created a new container called demo and unfortunately I get the same results

>{"time":"2024-06-04T03:23:11.920499965Z","level":"INFO","msg":"SQL query executed [15.584449ms]","app":"workout-tracker","version":"v0.15.0","sha":"0fe05a807206885e10716cad2f1978d995331c5c","module":"database","query":"INSERT INTO `map_data` (`created_at`,`updated_at`,`deleted_at`,`workout_id`,`creator`,`name`,`center`,`address`,`total_distance`,`total_duration`,`max_speed`,`pause_duration`,`min_elevation`,`max_elevation`,`total_up`,`total_down`,`points`) VALUES (\"2024-06-04 03:23:11.904\",\"2024-06-04 03:23:11.904\",NULL,4,\"RunnerUp SM-A525M\",\"RunnerUp-Running-2024-06-01T13:57:31Z\",\"{\"\"Lat\"\":19.484092458715782,\"\"Lng\"\":-99.12433610871645}\",NULL,3094.402307518108,2167000000000,5.241230479192305,374000000374,2230.980868580703,2243.626868580703,146.10838000000558,144.81988000000547,NULL) ON CONFLICT (`id`) DO UPDATE SET `workout_id`=`excluded`.`workout_id` RETURNING `id`","duration":15584449,"rows":1,"file":"/app/pkg/database/workouts.go:202"}

![imagen](https://github.com/jovandeginste/workout-tracker/assets/90874504/3a31d521-f865-4a21-9ba1-a3e2fd87a957)

**Comment by jovandeginste** [comment]
Suddenly I can reproduce the issue!

**Comment by jovandeginste** [comment]
I added a (partial) fix in #164 - would you please try this build?

**Comment by jovandeginste** [comment]
Also see: https://github.com/codingsince1985/geo-golang/issues/78

**Comment by nrevolt** [comment]
Switched back to repository: ghcr.io/jovandeginste/workout-tracker:master
which I believe contains the partial fix (please correct me if I am not
doing this correctly). Deleted the workout associated with  the attached
GPX and problem persists. Assuming it has to do with the geocoder issue you
mentioned.

Here is the debug info:


   - time=2024-06-04T10:56:46.196783248-04:00
   - level=INFO
   - msg=SQL query executed [72.653966ms]
   - app=workout-tracker
   - version=master
   - sha=fb0b77da206f023456701462bfaa18517773c9b2
   - module=database
   - query=INSERT INTO `map_data`
   (`created_at`,`updated_at`,`deleted_at`,`workout_id`,`creator`,`name`,`center`,`address`,`total_distance`,`total_duration`,`max_speed`,`pause_duration`,`min_elevation`,`max_elevation`,`total_up`,`total_down`,`points`)
   VALUES ("2024-06-04 10:56:46.123","2024-06-04
   10:56:46.123",NULL,57,"Samsung
   Health_0.2","20240602_145616.gpx","{""Lat"":43.704567668544406,""Lng"":-79.2816287506536}",NULL,3114.388558754279,2267000000000,1.7520393175928026,35000000035,146.10392938637222,166.61592938637222,33.67850000000007,32.57950000000008,NULL)
   ON CONFLICT (`id`) DO UPDATE SET `workout_id`=`excluded`.`workout_id`
   RETURNING `id`
   - duration=72653966
   - rows=1
   - file=/app/pkg/database/workouts.go:212

**Comment by betov69** [comment]
> I added a (partial) fix in #164 - would you please try this build?

Unfortunately it still doesn't work


![imagen](https://github.com/jovandeginste/workout-tracker/assets/90874504/5e4ea77c-f3cc-4b17-ac40-f072a0f2417d)

**Comment by jovandeginste** [comment]
There should now be log lines if a timeout happens

**Comment by betov69** [comment]
I show the logs

>{"time":"2024-06-04T16:48:03.270237529Z","level":"INFO","msg":"SQL query executed [15.044596ms]","app":"workout-tracker","version":"master","sha":"fb0b77da206f023456701462bfaa18517773c9b2","module":"database","query":"INSERT INTO `map_data` (`created_at`,`updated_at`,`deleted_at`,`workout_id`,`creator`,`name`,`center`,`address`,`total_distance`,`total_duration`,`max_speed`,`pause_duration`,`min_elevation`,`max_elevation`,`total_up`,`total_down`,`points`) VALUES (\"2024-06-04 16:48:03.255\",\"2024-06-04 16:48:03.255\",NULL,7,\"RunnerUp SM-A525M\",\"RunnerUp-Running-2024-06-01T13:57:31Z\",\"{\"\"Lat\"\":19.484092458715782,\"\"Lng\"\":-99.12433610871645}\",NULL,3094.402307518108,2167000000000,5.241230479192305,374000000374,2230.980868580703,2243.626868580703,146.10838000000558,144.81988000000547,NULL) ON CONFLICT (`id`) DO UPDATE SET `workout_id`=`excluded`.`workout_id` RETURNING `id`","duration":15044596,"rows":1,"file":"/app/pkg/database/workouts.go:212"}
{"time":"2024-06-04T16:48:03.273025671Z","level":"INFO","msg":"SQL query executed [2.476459ms]","app":"workout-tracker","version":"master","sha":"fb0b77da206f023456701462bfaa18517773c9b2","module":"database","query":"INSERT INTO `gpx_data` (`created_at`,`updated_at`,`deleted_at`,`workout_id`,`content`,`checksum`,`filename`) VALUES (\"2024-06-04 16:48:03.27\",\"2024-06-04 16:48:03.27\",NULL,7,\"<binary>\",\"<binary>\",\"RunnerUp_SM-A525M_2024-06-01-07-57-31_Running.gpx\") ON CONFLICT (`id`) DO UPDATE SET `workout_id`=`excluded`.`workout_id` RETURNING `id`","duration":2476459,"rows":1,"file":"/app/pkg/database/workouts.go:212"}

**Comment by jovandeginste** [comment]
No single log line containing "OpenStreetMap" ?

**Comment by nrevolt** [comment]
Only 2 lines from most current import contained "OpenStreetMap" as per below, and only the 1 

2024-06-04T22:21:02.044068762Z {"time":"2024-06-04T18:21:02.043997282-04:00","level":"INFO","prefix":"-","file":"workouts_map.go","line":"177","message":"OpenStreetMap reverse geocoding {43.711251, -79.298477}"}

2024-06-04T22:21:02.447613162Z {"time":"2024-06-04T18:21:02.447400155-04:00","level":"ERROR","prefix":"-","file":"workouts_map.go","line":"189","message":"OpenStreetMap geocoding error: invalid character '<' looking for beginning of value"}

**Comment by jovandeginste** [comment]
Seems like the issue described here: codingsince1985/geo-golang#78

**Comment by jovandeginste** [comment]
Please let me know if this is working for you @nrevolt and @betov69

**Comment by nrevolt** [comment]
Problem appears to have been resolved. Thank you.

**Comment by betov69** [comment]
> Please let me know if this is working for you @nrevolt and @betov69

I confirm that the incident has been corrected, thank you very much

![imagen](https://github.com/jovandeginste/workout-tracker/assets/90874504/31d33fba-46e9-48ce-ac9a-c19615aa095a)
