### ISSUE TITLE
Location not show in Workout

### ISSUE THREAD

**Issue by betov69** [jovandeginste/workout-tracker#334]
Hello, I just updated the workout container and the location is not displayed in the workouts section, in the screenshots I can see that the location is visible from the training details, thanks and regards

![uI9wlKsv0l](https://github.com/user-attachments/assets/70907cad-0cc2-4ba9-86fa-55980163a25f)

**Comment by jovandeginste** [comment]
Can you go to your profile settings and click the "update everything" button?

**Comment by betov69** [comment]
> Can you go to your profile settings and click the "update everything" button?

Yes Sr!!

**Comment by jovandeginste** [comment]
And did it help? 😏

**Comment by betov69** [comment]
> And did it help? 😏

Only the Average Speed ​​was corrected

![firefox_dfep0ru21M](https://github.com/user-attachments/assets/89e6c05d-4347-49f0-98b4-4d3eb64a459c)

**Comment by jovandeginste** [comment]
I see the "update" icon (the spinning arrows) is still showing on those workouts; can you check the logs if there is anything there?

**Comment by betov69** [comment]
The logs not show nothing inusual:


2024-12-24T18:46:23.079996997Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:23.078533075Z","method":"GET","host":"workout.irrealidad.xyz","path":"/","query":"","params":{},"route":"/","ip":"140.84.178.67","referer":"","length":0} response={"time":"2024-12-24T18:46:23.079834397Z","latency":1301322,"status":302,"length":0}

2024-12-24T18:46:23.153216233Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:23.152495272Z","method":"GET","host":"workout.irrealidad.xyz","path":"/user/signout","query":"","params":{},"route":"/user/signout","ip":"140.84.178.67","referer":"","length":0} response={"time":"2024-12-24T18:46:23.153202193Z","latency":706961,"status":302,"length":0}

2024-12-24T18:46:23.171703783Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:23.161669727Z","method":"GET","host":"workout.irrealidad.xyz","path":"/user/signin","query":"","params":{},"route":"/user/signin","ip":"140.84.178.67","referer":"","length":0} response={"time":"2024-12-24T18:46:23.171692183Z","latency":10022456,"status":200,"length":4226}

2024-12-24T18:46:33.983402247Z INFO msg=Worker started... app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=worker

2024-12-24T18:46:33.984018248Z INFO msg=updateRouteSegments batch 0 app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=worker

2024-12-24T18:46:33.984628968Z INFO msg=Worker finished... app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=worker

2024-12-24T18:46:35.385509106Z WARN missing value in cookies | prefix=- file=routes.go line=124

2024-12-24T18:46:35.386244347Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:35.385456466Z","method":"GET","host":"workout.irrealidad.xyz","path":"/","query":"","params":{},"route":"/","ip":"189.188.200.211","referer":"","length":0} response={"time":"2024-12-24T18:46:35.386222827Z","latency":766401,"status":302,"length":0}

2024-12-24T18:46:35.434804184Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:35.434155023Z","method":"GET","host":"workout.irrealidad.xyz","path":"/user/signout","query":"","params":{},"route":"/user/signout","ip":"189.188.200.211","referer":"","length":0} response={"time":"2024-12-24T18:46:35.434791344Z","latency":636361,"status":302,"length":0}

2024-12-24T18:46:35.473473325Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:35.47052656Z","method":"GET","host":"workout.irrealidad.xyz","path":"/user/signin","query":"","params":{},"route":"/user/signin","ip":"189.188.200.211","referer":"","length":0} response={"time":"2024-12-24T18:46:35.473464125Z","latency":2937605,"status":200,"length":1422}

2024-12-24T18:46:35.639622828Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:35.635620262Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/output.css","query":"","params":{"*":"/output.css"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/user/signin","length":0} response={"time":"2024-12-24T18:46:35.639607268Z","latency":3987046,"status":200,"length":20809}

2024-12-24T18:46:35.648093121Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:35.64758144Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/common.js","query":"","params":{"*":"/common.js"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/user/signin","length":0} response={"time":"2024-12-24T18:46:35.648081081Z","latency":499641,"status":200,"length":827}

2024-12-24T18:46:35.649635964Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:35.64758096Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/htmx.min.js","query":"","params":{"*":"/dist/htmx.min.js"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/user/signin","length":0} response={"time":"2024-12-24T18:46:35.649626764Z","latency":2045804,"status":200,"length":15704}

2024-12-24T18:46:35.788569664Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:35.787889783Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dumbbell.png","query":"","params":{"*":"/dumbbell.png"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/user/signin","length":0} response={"time":"2024-12-24T18:46:35.788554944Z","latency":665201,"status":200,"length":11933}

2024-12-24T18:46:40.705634278Z WARN missing value in cookies | prefix=- file=routes.go line=124

2024-12-24T18:46:40.705765518Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:40.705571358Z","method":"GET","host":"workout.irrealidad.xyz","path":"/","query":"","params":{},"route":"/","ip":"159.54.142.196","referer":"","length":0} response={"time":"2024-12-24T18:46:40.705743358Z","latency":172040,"status":302,"length":0}

2024-12-24T18:46:40.708225202Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:40.707573041Z","method":"GET","host":"workout.irrealidad.xyz","path":"/user/signout","query":"","params":{},"route":"/user/signout","ip":"159.54.142.196","referer":"https://workout.irrealidad.xyz/","length":0} response={"time":"2024-12-24T18:46:40.708209002Z","latency":635961,"status":302,"length":0}

2024-12-24T18:46:40.713873491Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:40.711053567Z","method":"GET","host":"workout.irrealidad.xyz","path":"/user/signin","query":"","params":{},"route":"/user/signin","ip":"159.54.142.196","referer":"https://workout.irrealidad.xyz/user/signout","length":0} response={"time":"2024-12-24T18:46:40.713865291Z","latency":2811724,"status":200,"length":1417}

2024-12-24T18:46:40.716455535Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:40.715817574Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dumbbell.png","query":"","params":{"*":"/dumbbell.png"},"route":"/assets*","ip":"159.54.142.196","referer":"https://workout.irrealidad.xyz/user/signin","length":0} response={"time":"2024-12-24T18:46:40.716446975Z","latency":629401,"status":200,"length":11933}

2024-12-24T18:46:42.559838727Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:42.480338602Z","method":"POST","host":"workout.irrealidad.xyz","path":"/user/signin","query":"","params":{},"route":"/user/signin","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/user/signin","length":35} response={"time":"2024-12-24T18:46:42.559782647Z","latency":79444045,"status":302,"length":0}

2024-12-24T18:46:42.652086153Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:42.608496324Z","method":"GET","host":"workout.irrealidad.xyz","path":"/","query":"","params":{},"route":"/","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/user/signin","length":0} response={"time":"2024-12-24T18:46:42.652071033Z","latency":43574709,"status":200,"length":6872}

2024-12-24T18:46:42.838819048Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:42.828057431Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/fullcalendar.min.js","query":"","params":{"*":"/dist/fullcalendar.min.js"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/","length":0} response={"time":"2024-12-24T18:46:42.838800368Z","latency":10742937,"status":200,"length":81272}

2024-12-24T18:46:50.471606007Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:50.421234128Z","method":"GET","host":"workout.irrealidad.xyz","path":"/workouts","query":"","params":{},"route":"/workouts","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/","length":0} response={"time":"2024-12-24T18:46:50.471585607Z","latency":50351479,"status":200,"length":15876}

2024-12-24T18:46:58.95036643Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:58.856888163Z","method":"POST","host":"workout.irrealidad.xyz","path":"/workouts/185/share","query":"","params":{"id":"185"},"route":"/workouts/:id/share","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts","length":0} response={"time":"2024-12-24T18:46:58.95034863Z","latency":93460467,"status":302,"length":0}

2024-12-24T18:46:59.257435073Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:58.984714604Z","method":"GET","host":"workout.irrealidad.xyz","path":"/workouts/185","query":"","params":{"id":"185"},"route":"/workouts/:id","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts","length":0} response={"time":"2024-12-24T18:46:59.257411793Z","latency":272697189,"status":200,"length":98559}

2024-12-24T18:46:59.467568563Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:59.466618241Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/apexcharts.css","query":"","params":{"*":"/dist/apexcharts.css"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:46:59.467554563Z","latency":936322,"status":200,"length":2574}

2024-12-24T18:46:59.47202141Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:59.466672601Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/leaflet.css","query":"","params":{"*":"/dist/leaflet.css"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:46:59.47201045Z","latency":5337849,"status":200,"length":3537}

2024-12-24T18:46:59.474372494Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:59.466618241Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/leaflet.js","query":"","params":{"*":"/dist/leaflet.js"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:46:59.474359334Z","latency":7741093,"status":200,"length":42748}

2024-12-24T18:46:59.479784422Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:59.47869218Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/shareon.min.css","query":"","params":{"*":"/dist/shareon.min.css"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:46:59.479775262Z","latency":1083082,"status":200,"length":7008}

2024-12-24T18:46:59.479920702Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:59.479447782Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/shareon.iife.js","query":"","params":{"*":"/dist/shareon.iife.js"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:46:59.479912742Z","latency":465000,"status":200,"length":1317}

2024-12-24T18:46:59.480500063Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:59.480050143Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/map.js","query":"","params":{"*":"/map.js"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:46:59.480492783Z","latency":442640,"status":200,"length":1978}

2024-12-24T18:46:59.4912112Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:46:59.466672601Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/apexcharts.min.js","query":"","params":{"*":"/dist/apexcharts.min.js"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:46:59.49119392Z","latency":24521319,"status":200,"length":139019}

2024-12-24T18:47:00.484852081Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:47:00.484285121Z","method":"GET","host":"workout.irrealidad.xyz","path":"/assets/dist/images/layers-2x.png","query":"","params":{"*":"/dist/images/layers-2x.png"},"route":"/assets*","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/assets/dist/leaflet.css","length":0} response={"time":"2024-12-24T18:47:00.484838401Z","latency":553320,"status":200,"length":1287}

2024-12-24T18:47:13.803476768Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:47:13.751111046Z","method":"GET","host":"workout.irrealidad.xyz","path":"/workouts","query":"","params":{},"route":"/workouts","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:47:13.803456288Z","latency":52345242,"status":200,"length":15932}

2024-12-24T18:47:25.51426291Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:47:25.452403974Z","method":"POST","host":"workout.irrealidad.xyz","path":"/workouts/185/share","query":"","params":{"id":"185"},"route":"/workouts/:id/share","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts","length":0} response={"time":"2024-12-24T18:47:25.51424587Z","latency":61841856,"status":302,"length":0}

2024-12-24T18:47:25.81562958Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:47:25.543610196Z","method":"GET","host":"workout.irrealidad.xyz","path":"/workouts/185","query":"","params":{"id":"185"},"route":"/workouts/:id","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts","length":0} response={"time":"2024-12-24T18:47:25.81560838Z","latency":271998184,"status":200,"length":98559}

2024-12-24T18:47:33.985531873Z INFO msg=Worker started... app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=worker

2024-12-24T18:47:33.986131354Z INFO msg=updateRouteSegments batch 0 app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=worker

2024-12-24T18:47:33.986897996Z INFO msg=Worker finished... app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=worker

2024-12-24T18:47:48.146670439Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:47:48.098180324Z","method":"GET","host":"workout.irrealidad.xyz","path":"/workouts","query":"","params":{},"route":"/workouts","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/185","length":0} response={"time":"2024-12-24T18:47:48.146649879Z","latency":48469555,"status":200,"length":15934}

2024-12-24T18:47:52.996668957Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:47:52.992819111Z","method":"GET","host":"workout.irrealidad.xyz","path":"/workouts/add","query":"","params":{},"route":"/workouts/add","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts","length":0} response={"time":"2024-12-24T18:47:52.996645157Z","latency":3826046,"status":200,"length":2186}

2024-12-24T18:48:02.606881386Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:48:02.494274652Z","method":"POST","host":"workout.irrealidad.xyz","path":"/workouts","query":"","params":{},"route":"/workouts","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/add","length":838736} response={"time":"2024-12-24T18:48:02.606864466Z","latency":112589814,"status":302,"length":0}

2024-12-24T18:48:02.72575661Z INFO msg=Incoming request app=workout-tracker version=master sha=619ece797d14b32c26cf92d597f2f8d34d217a54 module=webserver request={"time":"2024-12-24T18:48:02.663790874Z","method":"GET","host":"workout.irrealidad.xyz","path":"/workouts","query":"","params":{},"route":"/workouts","ip":"189.188.200.211","referer":"https://workout.irrealidad.xyz/workouts/add","length":0} response={"time":"2024-12-24T18:48:02.72573197Z","latency":61941096,"status":200,"length":16119}

![firefox_cWnyOy7rpC](https://github.com/user-attachments/assets/963b8d4d-bf6e-42d6-b926-1130945b3824)

**Comment by jovandeginste** [comment]
In your last screenshot, the arrows are gone. I'm assuming an issue with geo location determination. Can you send me a sample gpx?

**Comment by betov69** [comment]
Sure,
[RunnerUp_PVG100_2024-12-21-08-07-46_Running.zip](https://github.com/user-attachments/files/18246681/RunnerUp_PVG100_2024-12-21-08-07-46_Running.zip)

**Comment by jovandeginste** [comment]
When I upload the workout, the location seems to be detected:

![image](https://github.com/user-attachments/assets/810063fc-e286-46fb-b6da-8c1e9b88deca)

There may be some issue with looking up addresses from your computer. You can try this:
- go to workouts
- add a new workout
- in the "manual" form, pick any type with location (eg. running)
- you see the manual fields appear, including "Location"
- start typing some partial addresses in the location field
- they should be resolved to full options

![image](https://github.com/user-attachments/assets/5c5d5f37-c6c8-4a35-a088-e508f0c45f74)

If you don't see any results appearing, there must be something wrong with the geolocation service I use (https://nominatim.openstreetmap.org/); you could try if you can access this API at all, if you know how.

**Comment by betov69** [comment]
Hola, en el entrenamiento manual si se muestra la información de mi ciudad, pero sigue sin mostrarse en los entrenamientos, saludos:

![firefox_d0puEQSPca](https://github.com/user-attachments/assets/34aa87a8-16ec-4bc1-ae16-ff6283033e83)

**Comment by jovandeginste** [comment]
I believe I found the reason; this has to do with the screen size. I now changed this to always show all details (or not show at all).

**Comment by betov69** [comment]
> I believe I found the reason; this has to do with the screen size. I now changed this to always show all details (or not show at all).

You are absolutely right, I have my browser's zoom at 130 due to vision problems, now I have changed it to 120 and the cities appear, an apology and thank you for your time and patience, greetings

![firefox_RKnUz0MXov](https://github.com/user-attachments/assets/6ee786f5-5f3a-4497-b38a-4343217e842a)
