### ISSUE TITLE
No static assets in native binary archive

### ISSUE THREAD

**Issue by AlphaJack** [jovandeginste/workout-tracker#8]
Hi, with the native installation process I noticed that I get 

```json
{"message":"Not Found"}
```

When I request <http://127.0.0.1:8080/assets/dist/fontawesome/css/all.min.css>

The binary packages only ship the go binary, not the static css and js files. However, the favicon is there:

![image](https://github.com/jovandeginste/workout-tracker/assets/19962243/1d783e41-fcdd-48a0-8bc5-fd1fb802720d)

---

Unrelated, is there an environment variable for the port and host to use?

I would like to create an AUR package for workout-tracker and include these variables in an environment file.

**Comment by jovandeginste** [comment]
I think I fixed this in the newest release. The static assets were there, but the content of the `dist` folder was not generated during the go-release action (and thus not included).

I also added a list of environment variables to the README.

**Comment by repomaa** [comment]
@jovandeginste I think the issue is back or still not fixed. I'm running the nixos packaged version 1.18.1 and assets under dist are missing.

**Comment by repomaa** [comment]
It works with the released binary. I'm guessing something needs to be changed in the nixos package source: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/wo/workout-tracker/package.nix#L26

**Comment by jovandeginste** [comment]
Okay, then this is not an issue here, but in nixpkgs. Thanks for reporting (in both repositories)
